# Generated by Django 3.1 on 2020-08-21 14:16

import datetime

from django.db import migrations

from itou.siaes.models import Siae


def fix_siae_source(apps, schema_editor):
    for siae in Siae.objects.filter(source=Siae.SOURCE_USER_CREATED):
        user = siae.created_by
        if user:
            if user.is_staff:
                # Siae created by our staff. Should be STAFF_CREATED.
                siae.source = Siae.SOURCE_STAFF_CREATED
                siae.save()
        else:
            # Siae created by a user which no longer exists.
            # This only happened before the "create siae" feature was
            # introduced and should no longer happen ever.
            assert siae.created_at.date() < datetime.date(2019, 12, 31)
            siae.source = Siae.SOURCE_STAFF_CREATED
            siae.save()


class Migration(migrations.Migration):

    dependencies = [
        ("siaes", "0028_auto_20200821_1616"),
    ]

    # Forward migration was deactivated on purpose.
    operations = [migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop)]
